/* eslint-disable */
/* auto-generated by scripts/generate-modules.ts — do not edit manually */

export type ResourceAction = "7343521162-20231004-47A70D8BD670-57__get" | "__get" | "activities__get" | "assign_cost_category_many__post" | "attachments__get" | "check__get" | "corrective_invoices__post" | "corrective_oss_invoices__post" | "costs__get" | "create" | "create_note_many__post" | "daily_revenues__post" | "delete" | "deliver_via_email__post" | "destroy_many__delete" | "details__get" | "document_requests__post" | "download_many__get" | "download_xml__get" | "final_invoices__post" | "fiscal_reports__post" | "get" | "incomes__get" | "integration__delete" | "integration__get" | "integration__post" | "internal_evidences__post" | "internal_invoices__post" | "invoices__post" | "list" | "margin_invoices__post" | "mark_as_accounted__put" | "next_number__get" | "oss_invoices__post" | "paid__post" | "paid_many__put" | "pdf__get" | "pdf_many__post" | "quick_payments__delete" | "quick_payments__get" | "quick_payments__post" | "selected__get" | "send__post" | "send_to_ksef__post" | "share_links__delete" | "share_links__get" | "share_links__post" | "share_links_prolong__post" | "status__get" | "unpaid_many__put" | "update" | "update_file_name_many__put" | "upload__post";

export type ResourceName = "account/activities" | "account/details" | "advance_invoices" | "async/advance_invoices/status" | "async/corrective_invoices" | "async/corrective_invoices/status/" | "async/corrective_oss_invoices" | "async/corrective_oss_invoices/status" | "async/daily_revenues" | "async/daily_revenues/status" | "async/final_invoices" | "async/final_invoices/status" | "async/fiscal_reports" | "async/fiscal_reports/status" | "async/incomes/pdf_many" | "async/internal_evidences" | "async/internal_evidences/status" | "async/internal_invoices" | "async/internal_invoices/status" | "async/invoices" | "async/invoices/status" | "async/margin_invoices" | "async/margin_invoices/status" | "async/oss_invoices" | "async/oss_invoices/status" | "bank_accounts" | "books" | "clients" | "corrective_invoices" | "corrective_oss_invoices" | "countries" | "daily_revenues" | "documents_markings/incomes" | "documents_markings/incomes/selected" | "documents/costs" | "documents/costs/assign_cost_category_many" | "documents/costs/create_note_many" | "documents/costs/destroy_many" | "documents/costs/download_many" | "documents/costs/paid_many" | "documents/costs/unpaid_many" | "documents/costs/update_file_name_many" | "documents/costs/upload" | "final_invoices" | "fiscal_reports" | "flat_rates" | "gtus" | "gtus/selected" | "income_taxes" | "insurance_fees" | "internal_evidences" | "internal_invoices" | "invoices" | "invoices/{id}/attachments" | "ksef/documents" | "ksef/documents/send" | "ksef/import/7343521162-20231004-47A70D8BD670-57" | "ksef/import/costs" | "ksef/import/incomes" | "ksef/integration" | "ksef2/documents" | "ksef2/documents/send" | "ksef2/import/7343521162-20231004-47A70D8BD670-57" | "ksef2/import/costs" | "ksef2/import/incomes" | "ksef2/integration" | "margin_invoices" | "moss_vat_rates" | "oss_invoices" | "payments/document_requests" | "products" | "saf_v7_files" | "transaction_kinds" | "vat_eu_taxes" | "vat_exemptions" | "vat_exemptions/selected" | "vat_rates";

export type ActionDef = {
  method: string;
  pathTemplate: string;
  wrapPayload?: boolean;
  requiresId?: boolean;
};

export type ResourceDefinition = {
  name: ResourceName;
  pathPrefix: string;
  singularName: string;
  actions: Record<string, ActionDef>;
};

export const RESOURCE_DEFINITIONS: Record<ResourceName, ResourceDefinition> = {
  "account/activities": {
    "name": "account/activities",
    "pathPrefix": "account/activities",
    "singularName": "activity",
    "actions": {
      "activities__get": {
        "method": "GET",
        "pathTemplate": "account/activities.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "account/details": {
    "name": "account/details",
    "pathPrefix": "account/details",
    "singularName": "detail",
    "actions": {
      "details__get": {
        "method": "GET",
        "pathTemplate": "account/details.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "advance_invoices": {
    "name": "advance_invoices",
    "pathPrefix": "advance_invoices",
    "singularName": "advance_invoice",
    "actions": {
      "create": {
        "method": "POST",
        "pathTemplate": "advance_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "advance_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "advance_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "advance_invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "advance_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "send_to_ksef__post": {
        "method": "POST",
        "pathTemplate": "advance_invoices/{id}/send_to_ksef.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "advance_invoices/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "advance_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "advance_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "advance_invoices/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "advance_invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/advance_invoices/status": {
    "name": "async/advance_invoices/status",
    "pathPrefix": "async/advance_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/advance_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/corrective_invoices": {
    "name": "async/corrective_invoices",
    "pathPrefix": "async/corrective_invoices",
    "singularName": "corrective_invoice",
    "actions": {
      "corrective_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/corrective_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/corrective_invoices/status/": {
    "name": "async/corrective_invoices/status/",
    "pathPrefix": "async/corrective_invoices/status/",
    "singularName": "",
    "actions": {
      "__get": {
        "method": "GET",
        "pathTemplate": "async/corrective_invoices/status/.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/corrective_oss_invoices": {
    "name": "async/corrective_oss_invoices",
    "pathPrefix": "async/corrective_oss_invoices",
    "singularName": "corrective_oss_invoice",
    "actions": {
      "corrective_oss_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/corrective_oss_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/corrective_oss_invoices/status": {
    "name": "async/corrective_oss_invoices/status",
    "pathPrefix": "async/corrective_oss_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/corrective_oss_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/daily_revenues": {
    "name": "async/daily_revenues",
    "pathPrefix": "async/daily_revenues",
    "singularName": "daily_revenue",
    "actions": {
      "daily_revenues__post": {
        "method": "POST",
        "pathTemplate": "async/daily_revenues.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/daily_revenues/status": {
    "name": "async/daily_revenues/status",
    "pathPrefix": "async/daily_revenues/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/daily_revenues/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/final_invoices": {
    "name": "async/final_invoices",
    "pathPrefix": "async/final_invoices",
    "singularName": "final_invoice",
    "actions": {
      "final_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/final_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/final_invoices/status": {
    "name": "async/final_invoices/status",
    "pathPrefix": "async/final_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/final_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/fiscal_reports": {
    "name": "async/fiscal_reports",
    "pathPrefix": "async/fiscal_reports",
    "singularName": "fiscal_report",
    "actions": {
      "fiscal_reports__post": {
        "method": "POST",
        "pathTemplate": "async/fiscal_reports.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/fiscal_reports/status": {
    "name": "async/fiscal_reports/status",
    "pathPrefix": "async/fiscal_reports/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/fiscal_reports/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/incomes/pdf_many": {
    "name": "async/incomes/pdf_many",
    "pathPrefix": "async/incomes/pdf_many",
    "singularName": "pdf_many",
    "actions": {
      "pdf_many__post": {
        "method": "POST",
        "pathTemplate": "async/incomes/pdf_many.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "check__get": {
        "method": "GET",
        "pathTemplate": "async/incomes/pdf_many/{id}/check.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "get": {
        "method": "GET",
        "pathTemplate": "async/incomes/pdf_many/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/internal_evidences": {
    "name": "async/internal_evidences",
    "pathPrefix": "async/internal_evidences",
    "singularName": "internal_evidence",
    "actions": {
      "internal_evidences__post": {
        "method": "POST",
        "pathTemplate": "async/internal_evidences.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/internal_evidences/status": {
    "name": "async/internal_evidences/status",
    "pathPrefix": "async/internal_evidences/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/internal_evidences/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/internal_invoices": {
    "name": "async/internal_invoices",
    "pathPrefix": "async/internal_invoices",
    "singularName": "internal_invoice",
    "actions": {
      "internal_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/internal_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/internal_invoices/status": {
    "name": "async/internal_invoices/status",
    "pathPrefix": "async/internal_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/internal_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/invoices": {
    "name": "async/invoices",
    "pathPrefix": "async/invoices",
    "singularName": "invoice",
    "actions": {
      "invoices__post": {
        "method": "POST",
        "pathTemplate": "async/invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "async/invoices/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/invoices/status": {
    "name": "async/invoices/status",
    "pathPrefix": "async/invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/margin_invoices": {
    "name": "async/margin_invoices",
    "pathPrefix": "async/margin_invoices",
    "singularName": "margin_invoice",
    "actions": {
      "margin_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/margin_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/margin_invoices/status": {
    "name": "async/margin_invoices/status",
    "pathPrefix": "async/margin_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/margin_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "async/oss_invoices": {
    "name": "async/oss_invoices",
    "pathPrefix": "async/oss_invoices",
    "singularName": "oss_invoice",
    "actions": {
      "oss_invoices__post": {
        "method": "POST",
        "pathTemplate": "async/oss_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "async/oss_invoices/status": {
    "name": "async/oss_invoices/status",
    "pathPrefix": "async/oss_invoices/status",
    "singularName": "statu",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "async/oss_invoices/status/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "bank_accounts": {
    "name": "bank_accounts",
    "pathPrefix": "bank_accounts",
    "singularName": "bank_account",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "bank_accounts.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "bank_accounts/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "bank_accounts.json",
        "wrapPayload": true,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "bank_accounts/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "bank_accounts/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "books": {
    "name": "books",
    "pathPrefix": "books",
    "singularName": "book",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "books.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "books/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "clients": {
    "name": "clients",
    "pathPrefix": "clients",
    "singularName": "client",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "clients.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "clients/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "clients.json",
        "wrapPayload": true,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "clients/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "clients/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "corrective_invoices": {
    "name": "corrective_invoices",
    "pathPrefix": "corrective_invoices",
    "singularName": "corrective_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "corrective_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "corrective_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "corrective_invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "corrective_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "send_to_ksef__post": {
        "method": "POST",
        "pathTemplate": "corrective_invoices/{id}/send_to_ksef.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "corrective_invoices/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "corrective_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "corrective_invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "corrective_invoices/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "corrective_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "create": {
        "method": "POST",
        "pathTemplate": "corrective_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "corrective_oss_invoices": {
    "name": "corrective_oss_invoices",
    "pathPrefix": "corrective_oss_invoices",
    "singularName": "corrective_oss_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "corrective_oss_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "corrective_oss_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "corrective_oss_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "corrective_oss_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "corrective_oss_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "create": {
        "method": "POST",
        "pathTemplate": "corrective_oss_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "countries": {
    "name": "countries",
    "pathPrefix": "countries",
    "singularName": "country",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "countries.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "daily_revenues": {
    "name": "daily_revenues",
    "pathPrefix": "daily_revenues",
    "singularName": "daily_revenue",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "daily_revenues/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "daily_revenues.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "daily_revenues/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "daily_revenues/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "daily_revenues/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "daily_revenues/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "create": {
        "method": "POST",
        "pathTemplate": "daily_revenues.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "documents_markings/incomes": {
    "name": "documents_markings/incomes",
    "pathPrefix": "documents_markings/incomes",
    "singularName": "income",
    "actions": {
      "incomes__get": {
        "method": "GET",
        "pathTemplate": "documents_markings/incomes.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "documents_markings/incomes/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "documents_markings/incomes/selected": {
    "name": "documents_markings/incomes/selected",
    "pathPrefix": "documents_markings/incomes/selected",
    "singularName": "selected",
    "actions": {
      "selected__get": {
        "method": "GET",
        "pathTemplate": "documents_markings/incomes/selected.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs": {
    "name": "documents/costs",
    "pathPrefix": "documents/costs",
    "singularName": "cost",
    "actions": {
      "costs__get": {
        "method": "GET",
        "pathTemplate": "documents/costs.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "documents/costs/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "documents/costs/assign_cost_category_many": {
    "name": "documents/costs/assign_cost_category_many",
    "pathPrefix": "documents/costs/assign_cost_category_many",
    "singularName": "assign_cost_category_many",
    "actions": {
      "assign_cost_category_many__post": {
        "method": "POST",
        "pathTemplate": "documents/costs/assign_cost_category_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/create_note_many": {
    "name": "documents/costs/create_note_many",
    "pathPrefix": "documents/costs/create_note_many",
    "singularName": "create_note_many",
    "actions": {
      "create_note_many__post": {
        "method": "POST",
        "pathTemplate": "documents/costs/create_note_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/destroy_many": {
    "name": "documents/costs/destroy_many",
    "pathPrefix": "documents/costs/destroy_many",
    "singularName": "destroy_many",
    "actions": {
      "destroy_many__delete": {
        "method": "DELETE",
        "pathTemplate": "documents/costs/destroy_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/download_many": {
    "name": "documents/costs/download_many",
    "pathPrefix": "documents/costs/download_many",
    "singularName": "download_many",
    "actions": {
      "download_many__get": {
        "method": "GET",
        "pathTemplate": "documents/costs/download_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/paid_many": {
    "name": "documents/costs/paid_many",
    "pathPrefix": "documents/costs/paid_many",
    "singularName": "paid_many",
    "actions": {
      "paid_many__put": {
        "method": "PUT",
        "pathTemplate": "documents/costs/paid_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/unpaid_many": {
    "name": "documents/costs/unpaid_many",
    "pathPrefix": "documents/costs/unpaid_many",
    "singularName": "unpaid_many",
    "actions": {
      "unpaid_many__put": {
        "method": "PUT",
        "pathTemplate": "documents/costs/unpaid_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/update_file_name_many": {
    "name": "documents/costs/update_file_name_many",
    "pathPrefix": "documents/costs/update_file_name_many",
    "singularName": "update_file_name_many",
    "actions": {
      "update_file_name_many__put": {
        "method": "PUT",
        "pathTemplate": "documents/costs/update_file_name_many.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "documents/costs/upload": {
    "name": "documents/costs/upload",
    "pathPrefix": "documents/costs/upload",
    "singularName": "upload",
    "actions": {
      "upload__post": {
        "method": "POST",
        "pathTemplate": "documents/costs/upload.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "final_invoices": {
    "name": "final_invoices",
    "pathPrefix": "final_invoices",
    "singularName": "final_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "final_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "final_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "final_invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "final_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "send_to_ksef__post": {
        "method": "POST",
        "pathTemplate": "final_invoices/{id}/send_to_ksef.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "final_invoices/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "final_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "final_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "final_invoices/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "final_invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "final_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "fiscal_reports": {
    "name": "fiscal_reports",
    "pathPrefix": "fiscal_reports",
    "singularName": "fiscal_report",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "fiscal_reports/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "fiscal_reports.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "fiscal_reports/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "fiscal_reports/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "fiscal_reports/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "mark_as_accounted__put": {
        "method": "PUT",
        "pathTemplate": "fiscal_reports/{id}/mark_as_accounted.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "fiscal_reports.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "flat_rates": {
    "name": "flat_rates",
    "pathPrefix": "flat_rates",
    "singularName": "flat_rate",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "flat_rates.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "gtus": {
    "name": "gtus",
    "pathPrefix": "gtus",
    "singularName": "gtu",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "gtus.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "gtus/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "gtus/selected": {
    "name": "gtus/selected",
    "pathPrefix": "gtus/selected",
    "singularName": "selected",
    "actions": {
      "selected__get": {
        "method": "GET",
        "pathTemplate": "gtus/selected.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "income_taxes": {
    "name": "income_taxes",
    "pathPrefix": "income_taxes",
    "singularName": "income_taxe",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "income_taxes.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "income_taxes/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "income_taxes/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "insurance_fees": {
    "name": "insurance_fees",
    "pathPrefix": "insurance_fees",
    "singularName": "insurance_fee",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "insurance_fees.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "insurance_fees/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "insurance_fees/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "internal_evidences": {
    "name": "internal_evidences",
    "pathPrefix": "internal_evidences",
    "singularName": "internal_evidence",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "internal_evidences/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "internal_evidences.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "internal_evidences/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "internal_evidences/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "internal_evidences/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "internal_evidences/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "create": {
        "method": "POST",
        "pathTemplate": "internal_evidences.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "internal_invoices": {
    "name": "internal_invoices",
    "pathPrefix": "internal_invoices",
    "singularName": "internal_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "internal_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "internal_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "internal_invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "internal_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "internal_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "mark_as_accounted__put": {
        "method": "PUT",
        "pathTemplate": "internal_invoices/{id}/mark_as_accounted.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "internal_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "invoices": {
    "name": "invoices",
    "pathPrefix": "invoices",
    "singularName": "invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "send_to_ksef__post": {
        "method": "POST",
        "pathTemplate": "invoices/{id}/send_to_ksef.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "share_links__post": {
        "method": "POST",
        "pathTemplate": "invoices/{id}/share_links.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "share_links__get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/share_links.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "share_links_prolong__post": {
        "method": "POST",
        "pathTemplate": "invoices/{id}/share_links/prolong.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "share_links__delete": {
        "method": "DELETE",
        "pathTemplate": "invoices/{id}/share_links.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "quick_payments__post": {
        "method": "POST",
        "pathTemplate": "invoices/{id}/quick_payments.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "quick_payments__get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/quick_payments.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "quick_payments__delete": {
        "method": "DELETE",
        "pathTemplate": "invoices/{id}/quick_payments.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "attachments__get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/attachments.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "invoices/{id}/attachments": {
    "name": "invoices/{id}/attachments",
    "pathPrefix": "invoices/{id}/attachments",
    "singularName": "attachment",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "invoices/{id}/attachments/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "ksef/documents": {
    "name": "ksef/documents",
    "pathPrefix": "ksef/documents",
    "singularName": "document",
    "actions": {
      "send__post": {
        "method": "POST",
        "pathTemplate": "ksef/documents/{id}/send.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "status__get": {
        "method": "GET",
        "pathTemplate": "ksef/documents/{id}/status.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "ksef/documents/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "ksef/documents/send": {
    "name": "ksef/documents/send",
    "pathPrefix": "ksef/documents/send",
    "singularName": "send",
    "actions": {
      "send__post": {
        "method": "POST",
        "pathTemplate": "ksef/documents/send.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef/import/7343521162-20231004-47A70D8BD670-57": {
    "name": "ksef/import/7343521162-20231004-47A70D8BD670-57",
    "pathPrefix": "ksef/import/7343521162-20231004-47A70D8BD670-57",
    "singularName": "7343521162-20231004-47A70D8BD670-57",
    "actions": {
      "7343521162-20231004-47A70D8BD670-57__get": {
        "method": "GET",
        "pathTemplate": "ksef/import/7343521162-20231004-47A70D8BD670-57.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef/import/costs": {
    "name": "ksef/import/costs",
    "pathPrefix": "ksef/import/costs",
    "singularName": "cost",
    "actions": {
      "costs__get": {
        "method": "GET",
        "pathTemplate": "ksef/import/costs.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef/import/incomes": {
    "name": "ksef/import/incomes",
    "pathPrefix": "ksef/import/incomes",
    "singularName": "income",
    "actions": {
      "incomes__get": {
        "method": "GET",
        "pathTemplate": "ksef/import/incomes.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef/integration": {
    "name": "ksef/integration",
    "pathPrefix": "ksef/integration",
    "singularName": "integration",
    "actions": {
      "integration__post": {
        "method": "POST",
        "pathTemplate": "ksef/integration.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "integration__get": {
        "method": "GET",
        "pathTemplate": "ksef/integration.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "integration__delete": {
        "method": "DELETE",
        "pathTemplate": "ksef/integration.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef2/documents": {
    "name": "ksef2/documents",
    "pathPrefix": "ksef2/documents",
    "singularName": "document",
    "actions": {
      "send__post": {
        "method": "POST",
        "pathTemplate": "ksef2/documents/{id}/send.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "status__get": {
        "method": "GET",
        "pathTemplate": "ksef2/documents/{id}/status.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "ksef2/documents/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "ksef2/documents/send": {
    "name": "ksef2/documents/send",
    "pathPrefix": "ksef2/documents/send",
    "singularName": "send",
    "actions": {
      "send__post": {
        "method": "POST",
        "pathTemplate": "ksef2/documents/send.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef2/import/7343521162-20231004-47A70D8BD670-57": {
    "name": "ksef2/import/7343521162-20231004-47A70D8BD670-57",
    "pathPrefix": "ksef2/import/7343521162-20231004-47A70D8BD670-57",
    "singularName": "7343521162-20231004-47A70D8BD670-57",
    "actions": {
      "7343521162-20231004-47A70D8BD670-57__get": {
        "method": "GET",
        "pathTemplate": "ksef2/import/7343521162-20231004-47A70D8BD670-57.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef2/import/costs": {
    "name": "ksef2/import/costs",
    "pathPrefix": "ksef2/import/costs",
    "singularName": "cost",
    "actions": {
      "costs__get": {
        "method": "GET",
        "pathTemplate": "ksef2/import/costs.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef2/import/incomes": {
    "name": "ksef2/import/incomes",
    "pathPrefix": "ksef2/import/incomes",
    "singularName": "income",
    "actions": {
      "incomes__get": {
        "method": "GET",
        "pathTemplate": "ksef2/import/incomes.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "ksef2/integration": {
    "name": "ksef2/integration",
    "pathPrefix": "ksef2/integration",
    "singularName": "integration",
    "actions": {
      "integration__get": {
        "method": "GET",
        "pathTemplate": "ksef2/integration.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "margin_invoices": {
    "name": "margin_invoices",
    "pathPrefix": "margin_invoices",
    "singularName": "margin_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "margin_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "margin_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "margin_invoices/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "margin_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "send_to_ksef__post": {
        "method": "POST",
        "pathTemplate": "margin_invoices/{id}/send_to_ksef.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "download_xml__get": {
        "method": "GET",
        "pathTemplate": "margin_invoices/{id}/download_xml.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "margin_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "margin_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "margin_invoices/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "margin_invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "margin_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "moss_vat_rates": {
    "name": "moss_vat_rates",
    "pathPrefix": "moss_vat_rates",
    "singularName": "moss_vat_rate",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "moss_vat_rates.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "oss_invoices": {
    "name": "oss_invoices",
    "pathPrefix": "oss_invoices",
    "singularName": "oss_invoice",
    "actions": {
      "get": {
        "method": "GET",
        "pathTemplate": "oss_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "list": {
        "method": "GET",
        "pathTemplate": "oss_invoices.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "oss_invoices/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "pdf__get": {
        "method": "GET",
        "pathTemplate": "oss_invoices/{id}/pdf.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "deliver_via_email__post": {
        "method": "POST",
        "pathTemplate": "oss_invoices/{id}/deliver_via_email.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "next_number__get": {
        "method": "GET",
        "pathTemplate": "oss_invoices/next_number.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "create": {
        "method": "POST",
        "pathTemplate": "oss_invoices.json",
        "wrapPayload": true,
        "requiresId": false
      }
    }
  },
  "payments/document_requests": {
    "name": "payments/document_requests",
    "pathPrefix": "payments/document_requests",
    "singularName": "document_request",
    "actions": {
      "document_requests__post": {
        "method": "POST",
        "pathTemplate": "payments/document_requests.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "products": {
    "name": "products",
    "pathPrefix": "products",
    "singularName": "product",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "products.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "products/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "create": {
        "method": "POST",
        "pathTemplate": "products.json",
        "wrapPayload": true,
        "requiresId": false
      },
      "update": {
        "method": "PUT",
        "pathTemplate": "products/{id}.json",
        "wrapPayload": true,
        "requiresId": true
      },
      "delete": {
        "method": "DELETE",
        "pathTemplate": "products/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "saf_v7_files": {
    "name": "saf_v7_files",
    "pathPrefix": "saf_v7_files",
    "singularName": "saf_v7_file",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "saf_v7_files.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "saf_v7_files/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      },
      "paid__post": {
        "method": "POST",
        "pathTemplate": "saf_v7_files/{id}/paid.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "transaction_kinds": {
    "name": "transaction_kinds",
    "pathPrefix": "transaction_kinds",
    "singularName": "transaction_kind",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "transaction_kinds.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "vat_eu_taxes": {
    "name": "vat_eu_taxes",
    "pathPrefix": "vat_eu_taxes",
    "singularName": "vat_eu_taxe",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "vat_eu_taxes.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "vat_eu_taxes/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "vat_exemptions": {
    "name": "vat_exemptions",
    "pathPrefix": "vat_exemptions",
    "singularName": "vat_exemption",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "vat_exemptions.json",
        "wrapPayload": false,
        "requiresId": false
      },
      "get": {
        "method": "GET",
        "pathTemplate": "vat_exemptions/{id}.json",
        "wrapPayload": false,
        "requiresId": true
      }
    }
  },
  "vat_exemptions/selected": {
    "name": "vat_exemptions/selected",
    "pathPrefix": "vat_exemptions/selected",
    "singularName": "selected",
    "actions": {
      "selected__get": {
        "method": "GET",
        "pathTemplate": "vat_exemptions/selected.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  },
  "vat_rates": {
    "name": "vat_rates",
    "pathPrefix": "vat_rates",
    "singularName": "vat_rate",
    "actions": {
      "list": {
        "method": "GET",
        "pathTemplate": "vat_rates.json",
        "wrapPayload": false,
        "requiresId": false
      }
    }
  }
} as Record<ResourceName, ResourceDefinition>;
